source "https://rubygems.org"

# Comment out the Jekyll gem
# gem "jekyll", "~> 4.3.2"
# gem "just-the-docs", "~> 0.5.0"

# Use github-pages gem for GitHub Pages
gem "github-pages", "~> 228", group: :jekyll_plugins
gem "jekyll-remote-theme"

# Plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end 